<?php

namespace GalerieBundle\Repository;

/**
 * DiapoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiapoRepository extends \Doctrine\ORM\EntityRepository
{
}
